# 데이터 준비 : 파일에서 데이터 읽어들이기
#### CSV 파일이란
- comma seperated value
#### CSV 파일 읽어들이기
- 파일열기 > 파일읽기 > 표의 헤더 제거 > 리스트로 변환 (4단계)
- CSV 파일을 다루려면 CSV 라이브러리가 필요합니다. import csv
- 한 주피터 노트북 파일에서는 한 번만 import하면 셀마다 import 할 필요 없음!

In [1]:
import pandas as pd

In [2]:
pd.read_csv('card.csv', encoding='utf-8')

,이용일시,승인번호,본인구분,브랜드,이용카드,가맹점명,이용금액,이용구분,매입상태
0,2019/10/12 09:13,1972753,본,S&,185,네이버파이낸셜(주),546800,일시불(A),부분취소
1,2019/10/12 11:56,3399357,본,S&,185,GS 샵,60440,일시불(A),전표매입
2,2019/10/13 09:16,12621902,본,S&,185,G마켓,91520,P(A),전표매입
3,2019/10/14 01:32,20726947,본,S&,185,11번가,89810,일시불(A),전표매입
4,2019/10/14 07:06,21234320,본,S&,185,네이버파이낸셜(주),33600,일시불(A),전표매입
...,...,...,...,...,...,...,...,...,...
232,2019/12/30 17:59,11171348,본,S&,185,카페마마스 강남역지점,16800,일시불,전표매입
233,2019/12/31 12:35,18054067,본,S&,185,(주)현대백화점목동점,51502,일시불,전표매입
234,2019/12/31 12:43,18170026,본,S&,185,(주)현대백화점목동점,9200,일시불,전표매입
235,2019/12/31 12:50,18277034,본,S&,185,(주)현대백화점목동점,15000,일시불,전표매입
236,2019/12/31 14:12,19443195,본,S&,185,쿠팡,16640,일시불,전표매입